services:
 - type: web
    name: flask-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true

  - type: web
    name: frontend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build # Adjust based on how you build your frontend
    startCommand: serve -s build
    autoDeploy: true
